-- Astrolabe M3: Supabaseを一次台帳にする初期スキーマ。
-- eventsはINSERT/SELECTだけを許可し、UPDATE/DELETEはトリガーでも拒否する。

create table if not exists public.events (
  id bigint generated by default as identity primary key,
  ts timestamptz not null,
  type text not null check (
    type in (
      'proposed', 'selected', 'dismissed', 'marked_known', 'task_created',
      'task_done', 'quiz_result', 'interview', 'chat_note'
    )
  ),
  concept_id text,
  payload jsonb not null default '{}'::jsonb
);
create index if not exists events_type_idx on public.events(type);

create table if not exists public.concepts (
  id text primary key,
  name text not null,
  kind text not null default 'concept',
  status text not null default 'unknown',
  confidence double precision not null default 0.0 check (confidence between 0 and 1),
  summary text not null default '',
  source_urls jsonb not null default '[]'::jsonb check (jsonb_typeof(source_urls) = 'array'),
  first_seen timestamptz,
  last_touched timestamptz
);

create table if not exists public.edges (
  src text not null,
  dst text not null,
  type text not null check (type in ('prerequisite', 'related', 'derived_from', 'appeared_in')),
  weight double precision not null default 1.0,
  created_by text,
  created_at timestamptz,
  primary key (src, dst, type)
);

create table if not exists public.tasks (
  id bigint generated by default as identity primary key,
  concept_id text,
  title text not null,
  kind text not null,
  status text not null default 'open',
  est_minutes integer,
  evidence text,
  created_at timestamptz,
  done_at timestamptz
);

create table if not exists public.profile (
  id smallint primary key check (id = 1),
  interests jsonb not null default '{}'::jsonb,
  goals text not null default '',
  background text not null default '',
  time_budget text not null default ''
);

create table if not exists public.daily_reports (
  date date primary key,
  items jsonb not null,
  map_delta_text text not null default '',
  html_path text
);

create table if not exists public.llm_usage (
  usage_date date not null,
  run_id text not null,
  model_role text not null check (model_role in ('mini', 'flagship')),
  tokens bigint not null check (tokens >= 0),
  recorded_at timestamptz not null default now(),
  primary key (usage_date, run_id, model_role)
);

create or replace function public.astrolabe_reject_event_mutation()
returns trigger
language plpgsql
as $$
begin
  raise exception 'events is append-only: % is forbidden', tg_op
    using errcode = '55000';
end;
$$;

drop trigger if exists events_append_only on public.events;
create trigger events_append_only
before update or delete on public.events
for each row execute function public.astrolabe_reject_event_mutation();

create or replace function public.astrolabe_import_events(p_events jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  incoming record;
  existing public.events%rowtype;
  max_event_id bigint;
begin
  if jsonb_typeof(p_events) <> 'array' then
    raise exception 'p_events must be a JSON array';
  end if;

  for incoming in
    select *
    from jsonb_to_recordset(p_events) as event_row(
      id bigint,
      ts timestamptz,
      type text,
      concept_id text,
      payload jsonb
    )
    order by id
  loop
    select * into existing from public.events where id = incoming.id;
    if found then
      if existing.ts is distinct from incoming.ts
        or existing.type is distinct from incoming.type
        or existing.concept_id is distinct from incoming.concept_id
        or existing.payload is distinct from coalesce(incoming.payload, '{}'::jsonb)
      then
        raise exception 'event id=% conflicts with existing content', incoming.id;
      end if;
    else
      insert into public.events(id, ts, type, concept_id, payload)
      values (
        incoming.id,
        incoming.ts,
        incoming.type,
        incoming.concept_id,
        coalesce(incoming.payload, '{}'::jsonb)
      );
    end if;
  end loop;

  select coalesce(max(id), 0) into max_event_id from public.events;
  if max_event_id = 0 then
    perform setval(pg_get_serial_sequence('public.events', 'id'), 1, false);
  else
    perform setval(pg_get_serial_sequence('public.events', 'id'), max_event_id, true);
  end if;

  return jsonb_build_object('events', (select count(*) from public.events));
end;
$$;

create or replace function public.astrolabe_replace_derived(
  p_concepts jsonb,
  p_edges jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  if jsonb_typeof(p_concepts) <> 'array' or jsonb_typeof(p_edges) <> 'array' then
    raise exception 'derived payloads must be JSON arrays';
  end if;

  delete from public.edges;
  delete from public.concepts;

  insert into public.concepts(
    id, name, kind, status, confidence, summary, source_urls, first_seen, last_touched
  )
  select
    row.id,
    row.name,
    coalesce(row.kind, 'concept'),
    coalesce(row.status, 'unknown'),
    coalesce(row.confidence, 0.0),
    coalesce(row.summary, ''),
    coalesce(row.source_urls, '[]'::jsonb),
    row.first_seen,
    row.last_touched
  from jsonb_to_recordset(p_concepts) as row(
    id text,
    name text,
    kind text,
    status text,
    confidence double precision,
    summary text,
    source_urls jsonb,
    first_seen timestamptz,
    last_touched timestamptz
  );

  insert into public.edges(src, dst, type, weight, created_by, created_at)
  select
    row.src,
    row.dst,
    row.type,
    coalesce(row.weight, 1.0),
    row.created_by,
    row.created_at
  from jsonb_to_recordset(p_edges) as row(
    src text,
    dst text,
    type text,
    weight double precision,
    created_by text,
    created_at timestamptz
  );

  return jsonb_build_object(
    'concepts', (select count(*) from public.concepts),
    'edges', (select count(*) from public.edges)
  );
end;
$$;

create or replace function public.astrolabe_record_interview(
  p_profile jsonb,
  p_events jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  inserted_ids jsonb;
begin
  insert into public.profile(id, interests, goals, background, time_budget)
  values (
    1,
    coalesce(p_profile->'interests', '{}'::jsonb),
    coalesce(p_profile->>'goals', ''),
    coalesce(p_profile->>'background', ''),
    coalesce(p_profile->>'time_budget', '')
  )
  on conflict (id) do update set
    interests = excluded.interests,
    goals = excluded.goals,
    background = excluded.background,
    time_budget = excluded.time_budget;

  with inserted as (
    insert into public.events(ts, type, concept_id, payload)
    select row.ts, row.type, row.concept_id, coalesce(row.payload, '{}'::jsonb)
    from jsonb_to_recordset(p_events) as row(
      ts timestamptz,
      type text,
      concept_id text,
      payload jsonb
    )
    returning id
  )
  select coalesce(jsonb_agg(id order by id), '[]'::jsonb)
  into inserted_ids
  from inserted;

  return inserted_ids;
end;
$$;

create or replace function public.astrolabe_import_state(
  p_profile jsonb,
  p_tasks jsonb,
  p_reports jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  max_task_id bigint;
begin
  if p_profile <> '{}'::jsonb then
    insert into public.profile(id, interests, goals, background, time_budget)
    values (
      1,
      coalesce(p_profile->'interests', '{}'::jsonb),
      coalesce(p_profile->>'goals', ''),
      coalesce(p_profile->>'background', ''),
      coalesce(p_profile->>'time_budget', '')
    )
    on conflict (id) do update set
      interests = excluded.interests,
      goals = excluded.goals,
      background = excluded.background,
      time_budget = excluded.time_budget;
  end if;

  insert into public.tasks(
    id, concept_id, title, kind, status, est_minutes, evidence, created_at, done_at
  )
  select
    row.id, row.concept_id, row.title, row.kind, row.status, row.est_minutes,
    row.evidence, row.created_at, row.done_at
  from jsonb_to_recordset(p_tasks) as row(
    id bigint,
    concept_id text,
    title text,
    kind text,
    status text,
    est_minutes integer,
    evidence text,
    created_at timestamptz,
    done_at timestamptz
  )
  on conflict (id) do update set
    concept_id = excluded.concept_id,
    title = excluded.title,
    kind = excluded.kind,
    status = excluded.status,
    est_minutes = excluded.est_minutes,
    evidence = excluded.evidence,
    created_at = excluded.created_at,
    done_at = excluded.done_at;

  insert into public.daily_reports(date, items, map_delta_text, html_path)
  select row.date, row.items, coalesce(row.map_delta_text, ''), row.html_path
  from jsonb_to_recordset(p_reports) as row(
    date date,
    items jsonb,
    map_delta_text text,
    html_path text
  )
  on conflict (date) do update set
    items = excluded.items,
    map_delta_text = excluded.map_delta_text,
    html_path = excluded.html_path;

  select coalesce(max(id), 0) into max_task_id from public.tasks;
  if max_task_id = 0 then
    perform setval(pg_get_serial_sequence('public.tasks', 'id'), 1, false);
  else
    perform setval(pg_get_serial_sequence('public.tasks', 'id'), max_task_id, true);
  end if;

  return jsonb_build_object(
    'tasks', (select count(*) from public.tasks),
    'reports', (select count(*) from public.daily_reports)
  );
end;
$$;

revoke update, delete, truncate on public.events from anon, authenticated, service_role;
grant select, insert on public.events to service_role;
grant usage, select on sequence public.events_id_seq to service_role;

grant select, insert, update, delete on
  public.concepts,
  public.edges,
  public.tasks,
  public.profile,
  public.daily_reports,
  public.llm_usage
to service_role;
grant usage, select on sequence public.tasks_id_seq to service_role;

revoke all on function public.astrolabe_import_events(jsonb) from public, anon, authenticated;
revoke all on function public.astrolabe_replace_derived(jsonb, jsonb) from public, anon, authenticated;
revoke all on function public.astrolabe_record_interview(jsonb, jsonb) from public, anon, authenticated;
revoke all on function public.astrolabe_import_state(jsonb, jsonb, jsonb) from public, anon, authenticated;
grant execute on function public.astrolabe_import_events(jsonb) to service_role;
grant execute on function public.astrolabe_replace_derived(jsonb, jsonb) to service_role;
grant execute on function public.astrolabe_record_interview(jsonb, jsonb) to service_role;
grant execute on function public.astrolabe_import_state(jsonb, jsonb, jsonb) to service_role;

-- 多層防御: service_role 以外(anon / authenticated)からの台帳アクセスを全面遮断する。
-- RLSは有効化のみでポリシーを作らない(=service_role以外は全拒否)。service_role は
-- BYPASSRLS を持つため運用には影響しない。M3③でUIを公開すると anon キーがWebバンドルに
-- 埋め込まれるため、このブロックがないと private 台帳が全公開になる。
alter table public.events enable row level security;
alter table public.concepts enable row level security;
alter table public.edges enable row level security;
alter table public.tasks enable row level security;
alter table public.profile enable row level security;
alter table public.daily_reports enable row level security;
alter table public.llm_usage enable row level security;

revoke all on public.events, public.concepts, public.edges, public.tasks,
  public.profile, public.daily_reports, public.llm_usage
from public, anon, authenticated;
revoke usage, select on sequence public.events_id_seq from public, anon, authenticated;
revoke usage, select on sequence public.tasks_id_seq from public, anon, authenticated;
